spring:
  datasource:
    url: jdbc:mysql://localhost:3306/jcibardo_blog
    username: root
    password: 'anas123456789'
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5Dialect
    database-platform: org.hibernate.dialect.MySQLDialect
  application:
    name: jcibardo-blog
server:
  port: 8081